{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ansible-ui.fullname" . }}
  labels:
    {{- include "ansible-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
{{- end }}
